apiVersion: v1
kind: ConfigMap
metadata:
  name: yikv-server-config
data:
  config.json: |
    {
      "db_path": "/data/db",
      "listen": "0.0.0.0:9000",
      "arena_seg_gb": 1,
      "arena_max_gb": 512,
      "exclusive_arena_lock": true,
      "admin_unix_socket": "/data/admin.sock",
      "kafka": {
        "default_brokers": "kafka:9092"
      }
    }
