apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yikv-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # storageClassName: standard   # set in overlay if your cluster needs it
