# automatically generated by the FlatBuffers compiler, do not modify

# namespace: yidiandb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PutBatchRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPutBatchRequest(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PutBatchRequest()
        x.Init(buf, n + offset)
        return x

    # PutBatchRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PutBatchRequest
    def Rows(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from yidiandb.Row import Row
            obj = Row()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PutBatchRequest
    def RowsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PutBatchRequest
    def RowsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # PutBatchRequest
    def TableName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def PutBatchRequestStart(builder): builder.StartObject(2)
def PutBatchRequestAddRows(builder, rows): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(rows), 0)
def PutBatchRequestStartRowsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def PutBatchRequestAddTableName(builder, tableName): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(tableName), 0)
def PutBatchRequestEnd(builder): return builder.EndObject()
