# automatically generated by the FlatBuffers compiler, do not modify

# namespace: yidiandb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GetResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsGetResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GetResponse()
        x.Init(buf, n + offset)
        return x

    # GetResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GetResponse
    def Found(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # GetResponse
    def Err(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GetResponse
    def Row(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from yidiandb.Row import Row
            obj = Row()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Nanoseconds spent in KV index Get() on the server (0 if lookup was skipped).
    # GetResponse
    def IndexGetNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def GetResponseStart(builder): builder.StartObject(4)
def GetResponseAddFound(builder, found): builder.PrependBoolSlot(0, found, 0)
def GetResponseAddErr(builder, err): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(err), 0)
def GetResponseAddRow(builder, row): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(row), 0)
def GetResponseAddIndexGetNs(builder, indexGetNs): builder.PrependUint64Slot(3, indexGetNs, 0)
def GetResponseEnd(builder): return builder.EndObject()
