# automatically generated by the FlatBuffers compiler, do not modify

# namespace: yidiandb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GetRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsGetRequest(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GetRequest()
        x.Init(buf, n + offset)
        return x

    # GetRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GetRequest
    def Pk(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def GetRequestStart(builder): builder.StartObject(1)
def GetRequestAddPk(builder, pk): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(pk), 0)
def GetRequestEnd(builder): return builder.EndObject()
