# automatically generated by the FlatBuffers compiler, do not modify

# namespace: yikv

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BatchGetResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsBatchGetResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BatchGetResponse()
        x.Init(buf, n + offset)
        return x

    # BatchGetResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BatchGetResponse
    def Rows(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from yikv.Row import Row
            obj = Row()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BatchGetResponse
    def RowsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BatchGetResponse
    def RowsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # BatchGetResponse
    def Err(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def BatchGetResponseStart(builder): builder.StartObject(2)
def BatchGetResponseAddRows(builder, rows): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(rows), 0)
def BatchGetResponseStartRowsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def BatchGetResponseAddErr(builder, err): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(err), 0)
def BatchGetResponseEnd(builder): return builder.EndObject()
