# automatically generated by the FlatBuffers compiler, do not modify

# namespace: yikv

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Row(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsRow(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Row()
        x.Init(buf, n + offset)
        return x

    # Row
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Row
    def Fields(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from yikv.FieldValue import FieldValue
            obj = FieldValue()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Row
    def FieldsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Row
    def FieldsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def RowStart(builder): builder.StartObject(1)
def RowAddFields(builder, fields): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(fields), 0)
def RowStartFieldsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def RowEnd(builder): return builder.EndObject()
