# automatically generated by the FlatBuffers compiler, do not modify

# namespace: yikv

class ValueType(object):
    NONE = 0
    BOOL = 1
    I32 = 2
    I64 = 3
    F32 = 4
    F64 = 5
    STRING = 6
    BYTES = 7
    ARR_I32 = 8
    ARR_I64 = 9
    ARR_F32 = 10
    ARR_F64 = 11
    ARR_STRING = 12

